import { NextResponse } from "next/server";
import { GitHubClient } from "@/lib/github/client";
import { createClient, createAdminClient } from "@/lib/supabase/server";

export async function POST(request: Request): Promise<NextResponse> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json(
      { data: null, error: { message: "Unauthorized", code: "UNAUTHORIZED" } },
      { status: 401 }
    );
  }

  try {
    const body: unknown = await request.json();
    if (!isRecord(body)) throw new Error("Invalid request body.");

    const pipelineRunId = asString(body.pipelineRunId);
    const projectId = asString(body.projectId);
    const title = asString(body.title) || "AccessDiff: Accessibility Fixes";
    const customBody = asString(body.body);

    if (!pipelineRunId || !projectId) {
      throw new Error("pipelineRunId and projectId are required.");
    }

    const admin = createAdminClient();

    // Get project info
    const { data: project } = await admin
      .from("projects")
      .select("github_repo, default_branch")
      .eq("id", projectId)
      .single();
    if (!project) throw new Error("Project not found.");

    // Get user GitHub token
    const { data: dbUser } = await admin
      .from("users")
      .select("github_token")
      .eq("id", user.id)
      .single();
    if (!dbUser?.github_token) throw new Error("GitHub token missing.");

    // Get fixes for this pipeline run to count them
    const { data: fixes } = await admin
      .from("fixes")
      .select("id, file_path, status")
      .eq("pipeline_run_id", pipelineRunId);

    const approvedFixes = (fixes ?? []).filter((f) => f.status === "approved" || f.status === "verified");
    const uniqueFiles = new Set(approvedFixes.map((f) => f.file_path));

    // Get issues addressed
    const { data: issues } = await admin
      .from("issues")
      .select("id")
      .eq("pipeline_run_id", pipelineRunId);

    // Build PR body
    const prBody = customBody || generatePRBody({
      pipelineRunId,
      fixCount: approvedFixes.length,
      issueCount: issues?.length ?? 0,
      files: Array.from(uniqueFiles),
    });

    const [owner, repo] = project.github_repo.split("/");
    const github = new GitHubClient(dbUser.github_token);

    const branchName = `accessdiff/fixes-${pipelineRunId.slice(0, 8)}`;

    // Create PR via GitHub API
    const pr = await github.createPullRequest(owner, repo, {
      title,
      body: prBody,
      head: branchName,
      base: project.default_branch ?? "main",
    });

    // Persist PR record in database
    const { data: prRecord, error: insertErr } = await admin
      .from("pull_requests")
      .insert({
        pipeline_run_id: pipelineRunId,
        project_id: projectId,
        user_id: user.id,
        github_pr_number: pr.number,
        github_pr_url: pr.html_url,
        title,
        body: prBody,
        status: pr.state,
        files_modified: uniqueFiles.size,
        issues_addressed: issues?.length ?? 0,
      })
      .select()
      .single();

    if (insertErr) {
      console.warn("[PR API] Failed to persist PR record:", insertErr.message);
    }

    return NextResponse.json({
      data: {
        id: prRecord?.id ?? null,
        prNumber: pr.number,
        prUrl: pr.html_url,
        title,
        status: pr.state,
        filesModified: uniqueFiles.size,
        issuesAddressed: issues?.length ?? 0,
      },
      error: null,
    });
  } catch (caught: unknown) {
    const message = caught instanceof Error ? caught.message : "Failed to create pull request.";
    return NextResponse.json(
      { data: null, error: { message, code: "PR_CREATE_FAILED" } },
      { status: 500 }
    );
  }
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null;
}

function asString(v: unknown): string {
  return typeof v === "string" ? v : "";
}

function generatePRBody(opts: {
  pipelineRunId: string;
  fixCount: number;
  issueCount: number;
  files: string[];
}): string {
  return `## 🔍 AccessDiff Accessibility Fixes

**Pipeline Run:** \`${opts.pipelineRunId.slice(0, 8)}\`

### Summary
- **${opts.issueCount}** accessibility violations detected
- **${opts.fixCount}** AI-generated fixes applied
- **${opts.files.length}** files modified

### Modified Files
${opts.files.map((f) => `- \`${f}\``).join("\n")}

### WCAG Compliance
All fixes target **WCAG 2.2 AA** conformance, addressing color contrast, ARIA attributes, keyboard navigation, and semantic HTML issues.

---
*Generated by [AccessDiff](https://github.com/kachamsiddarth/HackIndia) — AI-Powered Accessibility Engineering Platform*
`;
}
